// <auto-generated />
using System;
using AutokolcsonzoProjekt.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutokolcsonzoProjekt.Migrations
{
    [DbContext(typeof(KolcsonzoDbContext))]
    partial class KolcsonzoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Automegoszto.Models.Auto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Meghajtas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Rendszam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Uj")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ID");

                    b.ToTable("Autok");
                });

            modelBuilder.Entity("Automegoszto.Models.Berles", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AutoID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan>("Ig")
                        .HasColumnType("time(6)");

                    b.Property<decimal>("Tav")
                        .HasColumnType("decimal(5,2)");

                    b.Property<TimeSpan>("Tol")
                        .HasColumnType("time(6)");

                    b.HasKey("ID");

                    b.HasIndex("AutoID");

                    b.ToTable("Berlesek");
                });

            modelBuilder.Entity("Automegoszto.Models.Berles", b =>
                {
                    b.HasOne("Automegoszto.Models.Auto", "Auto")
                        .WithMany()
                        .HasForeignKey("AutoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auto");
                });
#pragma warning restore 612, 618
        }
    }
}
